{
 "title": "ioB PV Power Ahoy",
 "time": { "from": "now/d", "to": "now/d" },
 "refresh": "1m",
 "templating": {
  "list": [
   { "name": "kwhPrice", "query": "0.58" },
   { "name": "ahoyTopic", "query": "ahoy-dtu" },
   { "name": "ahoyInvertername", "query": "Hoymiles1, Hoymiles2" }
  ]
 },
 "panels": [
  { "title": "Overview", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "Power",
   "type": "stat",
   "gridPos": { "h": 4, "w": 3, "x": 0, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "watt" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "none" ], "type": "fill" }
     ],
     "measurement": "mqtt.0.ahoy-dtu.total.P_AC",
     "query": "SELECT last(\"value\") FROM \"mqtt_consumer\" WHERE (\"topic\" = '$ahoyTopic/$ahoyInvertername/ch0/P_AC') AND $timeFilter GROUP BY time($__interval)",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       }
      ]
     ]
    }
   ]
  },
  {
   "title": "Consumption",
   "type": "stat",
   "gridPos": { "h": 4, "w": 3, "x": 3, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "watt" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "none" ], "type": "fill" }
     ],
     "measurement": "shelly.0.SHPLG-S#123456#1.Relay0.Power",
     "query": "SELECT last(\"value\") FROM \"mqtt_consumer\" WHERE (\"topic\" = '$ahoyTopic/$ahoyInvertername/ch0/P_AC') AND $timeFilter GROUP BY time($__interval)",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       }
      ]
     ]
    },
    {
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "none" ], "type": "fill" }
     ],
     "measurement": "shelly.0.SHPLG-S#123456#1.Relay0.Power",
     "query": "SELECT last(\"value\") FROM \"mqtt_consumer\" WHERE (\"topic\" = '$ahoyTopic/$ahoyInvertername/ch0/P_AC') AND $timeFilter GROUP BY time($__interval)",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       }
      ]
     ]
    },
    {
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "none" ], "type": "fill" }
     ],
     "measurement": "shelly.0.SHPLG-S#123456#1.Relay0.Power",
     "query": "SELECT last(\"value\") FROM \"mqtt_consumer\" WHERE (\"topic\" = '$ahoyTopic/$ahoyInvertername/ch0/P_AC') AND $timeFilter GROUP BY time($__interval)",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       }
      ]
     ]
    },
    {
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "none" ], "type": "fill" }
     ],
     "measurement": "shelly.0.SHPLG-S#123456#1.Relay0.Power",
     "query": "SELECT last(\"value\") FROM \"mqtt_consumer\" WHERE (\"topic\" = '$ahoyTopic/$ahoyInvertername/ch0/P_AC') AND $timeFilter GROUP BY time($__interval)",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       }
      ]
     ]
    }
   ]
  },
  {
   "title": "Energy",
   "type": "stat",
   "gridPos": { "h": 4, "w": 3, "x": 6, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "watth" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "none" ], "type": "fill" }
     ],
     "measurement": "mqtt.0.ahoy-dtu.total.YieldDay",
     "query": "SELECT last(\"value\") FROM \"mqtt_consumer\" WHERE (\"topic\" = '$ahoyTopic/$ahoyInvertername/ch0/YieldDay') AND $timeFilter GROUP BY time($__interval)",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       }
      ]
     ]
    }
   ]
  },
  {
   "title": "Total Energy",
   "type": "stat",
   "gridPos": { "h": 4, "w": 3, "x": 9, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "kwatth" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "none" ], "type": "fill" }
     ],
     "measurement": "mqtt.0.ahoy-dtu.total.YieldTotal",
     "query": "SELECT last(\"value\") FROM \"mqtt_consumer\" WHERE (\"topic\" = '$ahoyTopic/$ahoyInvertername/ch0/YieldTotal') AND $timeFilter GROUP BY time($__interval)",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       }
      ]
     ]
    }
   ]
  },
  {
   "title": "Savings",
   "type": "stat",
   "gridPos": { "h": 4, "w": 2, "x": 12, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "currencyEUR" } },
   "options": { "reduceOptions": { "calcs": [ "diff" ] } },
   "targets": [
    {
     "alias": "difference",
     "groupBy": [
      { "params": [ "$interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "mqtt.0.ahoy-dtu.total.YieldDay",
     "query": "SELECT last(\"value\")  / 1000 * $kwhPrice FROM \"mqtt_consumer\" WHERE (\"topic\" = '$ahoyTopic/$ahoyInvertername/ch0/YieldDay') AND $timeFilter GROUP BY time($interval) fill(null)",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       },
       { "params": [ " / 1000 * $kwhPrice" ], "type": "math" }
      ]
     ]
    }
   ]
  },
  {
   "title": "Temperature",
   "type": "stat",
   "gridPos": { "h": 4, "w": 3, "x": 14, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "celsius" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "none" ], "type": "fill" }
     ],
     "measurement": "openweathermap.0.forecast.current.temperature",
     "query": "SELECT mean(\"temperature\") FROM \"weather\" WHERE (\"country\" =~ /^$country$/ AND \"city\" =~ /^$city$/) AND $timeFilter GROUP BY time($__interval) fill(null)",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       }
      ]
     ]
    }
   ]
  },
  {
   "title": "Cloudiness",
   "type": "stat",
   "gridPos": { "h": 4, "w": 3, "x": 17, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "none" ], "type": "fill" }
     ],
     "measurement": "openweathermap.0.forecast.current.clouds",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       }
      ]
     ]
    }
   ]
  },
  {
   "title": "Sunrise",
   "type": "stat",
   "gridPos": { "h": 4, "w": 2, "x": 20, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "dateTimeAsIsoNoDateIfToday" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "openweathermap.0.forecast.current.sunrise",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       }
      ]
     ]
    }
   ]
  },
  {
   "title": "Sunrise",
   "type": "stat",
   "gridPos": { "h": 4, "w": 2, "x": 22, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "dateTimeAsIsoNoDateIfToday" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "openweathermap.0.forecast.current.sunset",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       }
      ]
     ]
    }
   ]
  },
  {
   "title": "Power",
   "type": "timeseries",
   "gridPos": { "h": 10, "w": 24, "x": 0, "y": 5 },
   "fieldConfig": { "defaults": { "unit": "watt" } },
   "targets": [
    {
     "alias": "Power",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "mqtt.0.ahoy-dtu.total.P_AC",
     "query": "SELECT mean(\"value\") FROM \"mqtt_consumer\" WHERE (\"topic\" = '$ahoyTopic/$ahoyInvertername/ch0/P_AC') AND $timeFilter GROUP BY time($__interval) fill(null)",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    },
    {
     "alias": "Cloudiness",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "none" ], "type": "fill" }
     ],
     "measurement": "weather",
     "query": "SELECT mean(\"value\") FROM \"openweathermap.0.forecast.current.clouds\" WHERE $timeFilter GROUP BY time($__interval) fill(null)",
     "select": [
      [
       { "params": [ "cloudiness" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "tags": [
      { "key": "city", "operator": "=", "value": "Oberhaching" }
     ]
    }
   ]
  },
  {
   "title": "Daily Production",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 15 },
   "fieldConfig": { "defaults": { "unit": "watth" } },
   "targets": [
    {
     "alias": "Daily Production",
     "groupBy": [
      { "params": [ "1d" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "mqtt.0.ahoy-dtu.total.YieldDay",
     "query": "SELECT last(\"value\") FROM \"mqtt_consumer\" WHERE (\"topic\" = '$ahoyTopic/$ahoyInvertername/ch0/YieldDay') AND $timeFilter GROUP BY time(1d)",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       }
      ]
     ]
    },
    {
     "alias": "Cloudiness",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "openweathermap.0.forecast.current.clouds",
     "query": "SELECT mean(\"cloudiness\") FROM \"weather\" WHERE (\"country\" =~ /^$country$/ AND \"city\" =~ /^$city$/) AND $timeFilter GROUP BY time(1d), \"country\", \"city\" fill(none)",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    },
    {
     "alias": "Daily Production",
     "query": "SELECT last(\"value\") FROM \"mqtt_consumer\" WHERE (\"topic\" = '$ahoyTopic/$ahoyInvertername/ch0/YieldDay') AND $timeFilter GROUP BY time(1d)"
    }
   ]
  },
  {
   "title": "Details",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 23 },
   "collapsed": true,
   "panels": [
    {
     "title": "U AC",
     "type": "stat",
     "gridPos": { "h": 3, "w": 3, "x": 0, "y": 24 },
     "fieldConfig": { "defaults": { "unit": "volt" } },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "groupBy": [
        { "params": [ "$__interval" ], "type": "time" },
        { "params": [ "none" ], "type": "fill" }
       ],
       "measurement": "mqtt.0.ahoy-dtu.Hoymiles1.ch0.U_AC",
       "query": "SELECT last(\"value\") FROM \"mqtt_consumer\" WHERE (\"topic\" = '$ahoyTopic/$ahoyInvertername/ch0/U_AC') AND $timeFilter GROUP BY time($__interval) fill(null)",
       "select": [
        [
         { "params": [ "value" ], "type": "field" },
         {
          "params": [],
          "type": "last"
         }
        ]
       ]
      }
     ]
    },
    {
     "title": "F AC",
     "type": "stat",
     "gridPos": { "h": 3, "w": 3, "x": 3, "y": 24 },
     "fieldConfig": { "defaults": { "unit": "rothz" } },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "groupBy": [
        { "params": [ "$__interval" ], "type": "time" },
        { "params": [ "none" ], "type": "fill" }
       ],
       "measurement": "mqtt.0.ahoy-dtu.Hoymiles1.ch0.F_AC",
       "query": "SELECT last(\"value\") FROM \"mqtt_consumer\" WHERE (\"topic\" = '$ahoyTopic/$ahoyInvertername/ch0/F_AC') AND $timeFilter GROUP BY time($__interval) fill(null)",
       "select": [
        [
         { "params": [ "value" ], "type": "field" },
         {
          "params": [],
          "type": "last"
         }
        ]
       ]
      }
     ]
    },
    {
     "title": "Inverter Temp",
     "type": "stat",
     "gridPos": { "h": 3, "w": 3, "x": 6, "y": 24 },
     "fieldConfig": { "defaults": { "unit": "celsius" } },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "groupBy": [
        { "params": [ "$__interval" ], "type": "time" },
        { "params": [ "none" ], "type": "fill" }
       ],
       "measurement": "mqtt.0.ahoy-dtu.Hoymiles1.ch0.Temp",
       "query": "SELECT last(\"value\") FROM \"mqtt_consumer\" WHERE (\"topic\" = '$ahoyTopic/$ahoyInvertername/ch0/Temp') AND $timeFilter GROUP BY time($__interval) fill(null)",
       "select": [
        [
         { "params": [ "value" ], "type": "field" },
         {
          "params": [],
          "type": "last"
         }
        ]
       ]
      }
     ]
    },
    {
     "title": "Efficiency",
     "type": "stat",
     "gridPos": { "h": 3, "w": 3, "x": 9, "y": 24 },
     "fieldConfig": { "defaults": { "unit": "percent" } },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "groupBy": [
        { "params": [ "$__interval" ], "type": "time" },
        { "params": [ "none" ], "type": "fill" }
       ],
       "measurement": "mqtt.0.ahoy-dtu.Hoymiles1.ch0.Efficiency",
       "query": "SELECT last(\"value\") FROM \"mqtt_consumer\" WHERE (\"topic\" = '$ahoyTopic/$ahoyInvertername/ch0/Efficiency') AND $timeFilter GROUP BY time($__interval) fill(null)",
       "select": [
        [
         { "params": [ "value" ], "type": "field" },
         {
          "params": [],
          "type": "last"
         }
        ]
       ]
      }
     ]
    },
    {
     "title": "Power Limit",
     "type": "stat",
     "gridPos": { "h": 3, "w": 3, "x": 12, "y": 24 },
     "fieldConfig": { "defaults": { "unit": "percent" } },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "groupBy": [
        { "params": [ "$__interval" ], "type": "time" },
        { "params": [ "none" ], "type": "fill" }
       ],
       "measurement": "mqtt.0.ahoy-dtu.Hoymiles1.ch0.active_PowerLimit",
       "query": "SELECT last(\"value\") FROM \"mqtt_consumer\" WHERE (\"topic\" = '$ahoyTopic/$ahoyInvertername/ch0/PowerLimit') AND $timeFilter GROUP BY time($__interval) fill(null)",
       "select": [
        [
         { "params": [ "value" ], "type": "field" },
         {
          "params": [],
          "type": "last"
         }
        ]
       ]
      }
     ]
    },
    {
     "title": "Ahoy Uptime",
     "type": "stat",
     "gridPos": { "h": 3, "w": 3, "x": 15, "y": 24 },
     "fieldConfig": { "defaults": { "unit": "s" } },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "groupBy": [
        { "params": [ "$__interval" ], "type": "time" },
        { "params": [ "none" ], "type": "fill" }
       ],
       "measurement": "mqtt.0.ahoy-dtu.uptime",
       "query": "SELECT last(\"value\") FROM \"mqtt_consumer\" WHERE (\"topic\" = '$ahoyTopic/uptime') AND $timeFilter GROUP BY time($__interval) fill(null)",
       "select": [
        [
         { "params": [ "value" ], "type": "field" },
         {
          "params": [],
          "type": "last"
         }
        ]
       ]
      }
     ]
    },
    {
     "title": "Ahoy Wifi RSSI",
     "type": "stat",
     "gridPos": { "h": 3, "w": 3, "x": 18, "y": 24 },
     "fieldConfig": { "defaults": { "unit": "dBm" } },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "groupBy": [
        { "params": [ "$__interval" ], "type": "time" },
        { "params": [ "none" ], "type": "fill" }
       ],
       "measurement": "mqtt.0.ahoy-dtu.wifi_rssi",
       "query": "SELECT last(\"value\") FROM \"mqtt_consumer\" WHERE (\"topic\" = '$ahoyTopic/wifi_rssi') AND $timeFilter GROUP BY time($__interval) fill(null)",
       "select": [
        [
         { "params": [ "value" ], "type": "field" },
         {
          "params": [],
          "type": "last"
         }
        ]
       ]
      }
     ]
    },
    {
     "title": "MQTT",
     "type": "stat",
     "gridPos": { "h": 3, "w": 3, "x": 21, "y": 24 },
     "fieldConfig": { "defaults": { "unit": "string" } },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "groupBy": [
        { "params": [ "$__interval" ], "type": "time" },
        { "params": [ "null" ], "type": "fill" }
       ],
       "measurement": "mqtt.0.ahoy-dtu.mqtt",
       "query": "SELECT last(\"value\") FROM \"mqtt_consumer\" WHERE (\"topic\" = '$ahoyTopic/mqtt') AND $timeFilter GROUP BY time($__interval) fill(null)",
       "select": [
        [
         { "params": [ "value" ], "type": "field" },
         {
          "params": [],
          "type": "last"
         }
        ]
       ]
      }
     ]
    },
    {
     "title": "Last Message",
     "type": "stat",
     "gridPos": { "h": 2, "w": 6, "x": 0, "y": 27 },
     "fieldConfig": { "defaults": { "unit": "none" } },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "groupBy": [
        { "params": [ "$__interval" ], "type": "time" },
        { "params": [ "none" ], "type": "fill" }
       ],
       "measurement": "mqtt.0.ahoy-dtu.Hoymiles1.ch0.LastAlarmCode",
       "query": "SELECT mean(\"value\") FROM \"mqtt_consumer\" WHERE (\"topic\" = '$ahoyTopic/$ahoyInvertername/available') AND $timeFilter GROUP BY time($__interval) fill(null)",
       "select": [
        [
         { "params": [ "value" ], "type": "field" },
         {
          "params": [],
          "type": "mean"
         }
        ]
       ]
      }
     ]
    },
    {
     "title": "Inverter #0: Hoymiles1",
     "type": "stat",
     "gridPos": { "h": 2, "w": 6, "x": 6, "y": 27 },
     "fieldConfig": { "defaults": { "unit": "none" } },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "groupBy": [
        { "params": [ "$__interval" ], "type": "time" },
        { "params": [ "none" ], "type": "fill" }
       ],
       "measurement": "mqtt.0.ahoy-dtu.Hoymiles1.available",
       "query": "SELECT mean(\"value\") FROM \"mqtt_consumer\" WHERE (\"topic\" = '$ahoyTopic/$ahoyInvertername/available') AND $timeFilter GROUP BY time($__interval) fill(null)",
       "select": [
        [
         { "params": [ "value" ], "type": "field" },
         {
          "params": [],
          "type": "last"
         }
        ]
       ]
      }
     ]
    },
    {
     "title": "Ahoy Status",
     "type": "stat",
     "gridPos": { "h": 2, "w": 6, "x": 12, "y": 27 },
     "fieldConfig": { "defaults": { "unit": "string" } },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "groupBy": [
        { "params": [ "$__interval" ], "type": "time" },
        { "params": [ "none" ], "type": "fill" }
       ],
       "measurement": "mqtt.0.ahoy-dtu.status",
       "query": "SELECT last(\"value\") FROM \"mqtt_consumer\" WHERE (\"topic\" = '$ahoyTopic/$ahoyInvertername/available_text') AND $timeFilter GROUP BY time($__interval) fill(null)",
       "select": [
        [
         { "params": [ "value" ], "type": "field" },
         {
          "params": [],
          "type": "mean"
         }
        ]
       ]
      }
     ]
    },
    {
     "title": "last successful transmission",
     "type": "stat",
     "gridPos": { "h": 2, "w": 6, "x": 18, "y": 27 },
     "fieldConfig": { "defaults": { "unit": "dateTimeAsIso" } },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "groupBy": [
        { "params": [ "$__interval" ], "type": "time" },
        { "params": [ "none" ], "type": "fill" }
       ],
       "measurement": "mqtt.0.ahoy-dtu.Hoymiles1.last_success",
       "query": "SELECT last(\"value\") * 1000  FROM \"mqtt_consumer\" WHERE (\"topic\" = '$ahoyTopic/$ahoyInvertername/last_success') AND $timeFilter GROUP BY time($__interval) fill(null)",
       "select": [
        [
         { "params": [ "value" ], "type": "field" },
         {
          "params": [],
          "type": "last"
         }
        ]
       ]
      }
     ]
    },
    {
     "title": "Power",
     "type": "timeseries",
     "gridPos": { "h": 19, "w": 24, "x": 0, "y": 29 },
     "fieldConfig": { "defaults": { "unit": "watt" } },
     "targets": [
      {
       "alias": "Power Ost",
       "groupBy": [
        { "params": [ "$__interval" ], "type": "time" },
        { "params": [ "null" ], "type": "fill" }
       ],
       "measurement": "mqtt.0.ahoy-dtu.Hoymiles1.ch1.P_DC",
       "query": "SELECT mean(\"value\") FROM \"mqtt_consumer\" WHERE (\"topic\" = '$ahoyTopic/$ahoyInvertername/ch1/P_DC') AND $timeFilter GROUP BY time($__interval) fill(null)",
       "select": [
        [
         { "params": [ "value" ], "type": "field" },
         {
          "params": [],
          "type": "mean"
         }
        ]
       ]
      },
      {
       "alias": "Power West",
       "groupBy": [
        { "params": [ "$__interval" ], "type": "time" },
        { "params": [ "null" ], "type": "fill" }
       ],
       "measurement": "mqtt.0.ahoy-dtu.Hoymiles1.ch2.P_DC",
       "query": "SELECT mean(\"value\") FROM \"mqtt_consumer\" WHERE (\"topic\" = '$ahoyTopic/$ahoyInvertername/ch2/P_DC') AND $timeFilter GROUP BY time($__interval) fill(null)",
       "select": [
        [
         { "params": [ "value" ], "type": "field" },
         {
          "params": [],
          "type": "mean"
         }
        ]
       ]
      },
      {
       "alias": "Irridation Ost",
       "groupBy": [
        { "params": [ "$__interval" ], "type": "time" },
        { "params": [ "null" ], "type": "fill" }
       ],
       "measurement": "mqtt.0.ahoy-dtu.Hoymiles1.ch1.Irradiation",
       "query": "SELECT mean(\"value\") FROM \"mqtt_consumer\" WHERE (\"topic\" = '$ahoyTopic/$ahoyInvertername/ch1/Irradiation') AND $timeFilter GROUP BY time($__interval) fill(null)",
       "select": [
        [
         { "params": [ "value" ], "type": "field" },
         {
          "params": [],
          "type": "mean"
         }
        ]
       ]
      },
      {
       "alias": "Irridation West",
       "groupBy": [
        { "params": [ "$__interval" ], "type": "time" },
        { "params": [ "null" ], "type": "fill" }
       ],
       "measurement": "mqtt.0.ahoy-dtu.Hoymiles1.ch2.Irradiation",
       "query": "SELECT mean(\"value\") FROM \"mqtt_consumer\" WHERE (\"topic\" = '$ahoyTopic/$ahoyInvertername/ch2/Irradiation') AND $timeFilter GROUP BY time($__interval) fill(null)",
       "select": [
        [
         { "params": [ "value" ], "type": "field" },
         {
          "params": [],
          "type": "mean"
         }
        ]
       ]
      }
     ]
    },
    {
     "title": "Weekly Production",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 24, "x": 0, "y": 48 },
     "fieldConfig": { "defaults": { "unit": "kwatth" } },
     "targets": [
      {
       "alias": "Weekly Production",
       "groupBy": [
        { "params": [ "1d" ], "type": "time" }
       ],
       "measurement": "mqtt_consumer",
       "query": "SELECT sum(dtp) FROM (SELECT non_negative_difference(\"value\") AS dtp FROM \"mqtt.0.ahoy-dtu.total.YieldTotal\" WHERE  $timeFilter) GROUP BY time(1w)",
       "select": [
        [
         { "params": [ "value" ], "type": "field" },
         {
          "params": [],
          "type": "last"
         }
        ]
       ]
      },
      {
       "alias": "Cloudiness",
       "groupBy": [
        { "params": [ "$__interval" ], "type": "time" },
        { "params": [ "null" ], "type": "fill" }
       ],
       "measurement": "openweathermap.0.forecast.current.clouds",
       "query": "SELECT mean(\"cloudiness\") FROM \"weather\" WHERE (\"country\" =~ /^$country$/ AND \"city\" =~ /^$city$/) AND $timeFilter GROUP BY time(1w), \"country\", \"city\" fill(none)",
       "select": [
        [
         { "params": [ "value" ], "type": "field" },
         {
          "params": [],
          "type": "mean"
         }
        ]
       ]
      },
      {
       "alias": "Weekly Production",
       "query": "SELECT sum(dtp) FROM (SELECT non_negative_difference(\"value\") AS dtp FROM \"mqtt_consumer\" WHERE (\"topic\" = '$ahoyTopic/$ahoyInvertername/ch0/YieldTotal') AND $timeFilter) GROUP BY time(1w)"
      }
     ]
    }
   ]
  },
  {
   "title": "Balance",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 24 },
   "collapsed": true,
   "panels": [
    {
     "title": "Balance",
     "type": "timeseries",
     "gridPos": { "h": 10, "w": 24, "x": 0, "y": 25 },
     "fieldConfig": { "defaults": { "unit": "watt" } },
     "targets": [
      {
       "alias": "Power",
       "groupBy": [
        { "params": [ "$__interval" ], "type": "time" },
        { "params": [ "none" ], "type": "fill" }
       ],
       "measurement": "mqtt.0.ahoy-dtu.total.P_AC",
       "query": "SELECT mean(\"value\") FROM \"mqtt.0.ahoy-dtu.total.P_AC\" WHERE $timeFilter GROUP BY time($__interval) fill(none)",
       "select": [
        [
         { "params": [ "value" ], "type": "field" },
         {
          "params": [],
          "type": "mean"
         }
        ]
       ]
      },
      {
       "alias": "Thermomix",
       "groupBy": [
        { "params": [ "$__interval" ], "type": "time" },
        { "params": [ "null" ], "type": "fill" }
       ],
       "measurement": "shelly.0.SHPLG-S#123456#1.Relay0.Power",
       "select": [
        [
         { "params": [ "value" ], "type": "field" },
         {
          "params": [],
          "type": "mean"
         }
        ]
       ]
      },
      {
       "alias": "Kühlschrank",
       "groupBy": [
        { "params": [ "$__interval" ], "type": "time" },
        { "params": [ "null" ], "type": "fill" }
       ],
       "measurement": "shelly.0.SHPLG-S#123456#1.Relay0.Power",
       "select": [
        [
         { "params": [ "value" ], "type": "field" },
         {
          "params": [],
          "type": "mean"
         }
        ]
       ]
      },
      {
       "alias": "Büro",
       "groupBy": [
        { "params": [ "$__interval" ], "type": "time" },
        { "params": [ "null" ], "type": "fill" }
       ],
       "measurement": "shelly.0.SHPLG-S#123456#1.Relay0.Power",
       "select": [
        [
         { "params": [ "value" ], "type": "field" },
         {
          "params": [],
          "type": "mean"
         }
        ]
       ]
      },
      {
       "alias": "Internet",
       "groupBy": [
        { "params": [ "$__interval" ], "type": "time" },
        { "params": [ "null" ], "type": "fill" }
       ],
       "measurement": "shelly.0.SHPLG-S#123456#1.Relay0.Power",
       "select": [
        [
         { "params": [ "value" ], "type": "field" },
         {
          "params": [],
          "type": "mean"
         }
        ]
       ]
      }
     ]
    }
   ]
  }
 ]
}